#!/bin/sh
#chkconfig: 345 88 12
### BEGI INIT INFO
# Provides: sshd
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $syslog
# Should-Start: $syslog
# Should-Stop: $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start up the OpenSSH server daemon
# Description:       SSH is a protocol for secure remote shell access.
#		     This service starts up the OpenSSH server daemon.
### END INIT INFO
program=/root/deamon_main
#program=/usr/sbin/eqm-client
prog=${program##*/}
. /etc/rc.d/init.d/functions

RETVAL=0

start() {
	echo -n $"Start $prog: "
	$program start
#	while [ 1 ]; do
#		echo -n "sleep 1"
#		sleep 1
#	done	
	RETVAL=$?
	echo
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
##	sh $program stop
	killall -s SIGINT $program
	RETVAL=$?
	echo
	return $RETVAL
}

case "$1" in
start)
	start
	;;

stop)
	stop
#	echo "stop eqm service"
	;;

status)
	;;

*)
	echo "start | stop | status "
	exit 1	
esac
